version: '3.8'

services:
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "5000:5000"      # 예시: 백엔드가 5000번 포트 사용
    env_file:
      - ./BackEnd/.env   # 필요시 환경변수 파일 지정

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "3000:80"        # 예시: 프론트엔드(Nginx) 80포트를 호스트 3000번에 연결
    depends_on:
      - backend