name: Deploy Flask to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t flask-app ./BackEnd
      - name: Deploy to Oracle VM
        run: |
          scp -i ${{ secrets.SSH_KEY }} flask-app.tar ubuntu@144.24.71.122:~
          ssh -i ${{ secrets.SSH_KEY }} ubuntu@144.24.71.122 'docker load -i flask-app.tar && docker-compose up -d'
