name: Deploy to Oracle Cloud VM (self-hosted)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # VM에 동작하는 runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Pull latest images
        working-directory: /home/ubuntu
        run: |
          docker-compose pull

      - name: Restart services
        working-directory: /home/ubuntu
        run: |
          docker-compose up -d --pull always --force-recreate