name: Deploy to Oracle Cloud VM (self-hosted)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # VM에 동작하는 runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Stop and remove old containers
        working-directory: /home/ubuntu
        run: |
          docker-compose down

      - name: Pull latest images
        working-directory: /home/ubuntu
        run: |
          docker-compose pull

      - name: Start services
        working-directory: /home/ubuntu
        run: |
          docker-compose up -d --force-recreate --remove-orphans